<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-388</name>
   <tag></tag>
   <elementGuidId>48fbe48c-cfeb-4cbd-8082-742f52b96199</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-388</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-388']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ddf7397-eff5-4afc-a896-e4bf7c1bfd8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cd61248e-c9d2-4fff-917c-6f7605e4a5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-388</value>
      <webElementGuid>c21e199e-ce4a-4b05-b13f-e7ff0f3e6f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1ab68b29-ef5f-4378-aed9-e64566c30915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-388&quot;)</value>
      <webElementGuid>21d9847c-e6b5-4a0f-a648-6dd2b7cc4f10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-388']</value>
      <webElementGuid>66f4f5f0-2e89-4998-a825-2328a6844eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[4]/div/div/div/input</value>
      <webElementGuid>7049fc93-fa18-4ce5-b806-e7c9e52a9ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>8db09603-dfb0-41e2-b483-17ddcfd1d5ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-388' and @type = 'password']</value>
      <webElementGuid>6fd7908d-c942-4037-8294-48423099df95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
