<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_input-101</name>
   <tag></tag>
   <elementGuidId>40c0cd2b-8d68-4be2-8351-eced34a9ff27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-101']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-101</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d186c19-675a-4096-87d0-cb9c83525734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d5c816e6-b9bd-4593-a060-da1b18f7b62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-101</value>
      <webElementGuid>61a226e0-163b-44f6-9a92-fd0f2ff2db71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>09a925f6-24b2-438c-87b1-fe450fb40230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g @let's.moot</value>
      <webElementGuid>5e10acac-8597-44f6-bf38-ffbd53a2e1a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-101&quot;)</value>
      <webElementGuid>0a3f2b4c-1b22-4725-9dfb-924e29d3e9e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-101']</value>
      <webElementGuid>55167e2b-0ceb-4df9-9cf9-ccd96f233066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/div/div/div/div/div/div/div/form/div[3]/div/div/div/input</value>
      <webElementGuid>f02e1261-8abb-4128-a6ed-6a85017d139a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>b96a8f3e-b5ca-472c-a178-48b8483f3169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-101' and @type = 'text' and @placeholder = concat(&quot;e.g @let&quot; , &quot;'&quot; , &quot;s.moot&quot;)]</value>
      <webElementGuid>606d08fa-a664-4594-8995-51dc7c44e5f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
