<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_input-101</name>
   <tag></tag>
   <elementGuidId>39d9bf15-8a47-4bb3-9b89-bcc8e2ce9ccf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-101']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-101</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>639c3ec9-1df3-4004-94bf-7208a436b9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c0c39dd3-40ea-4cf6-b478-464c059d7236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-101</value>
      <webElementGuid>c7442776-6649-4c4c-b0cd-19945bdf71fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>17854be2-d510-4727-a37d-8bd24c812687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g @let's.moot</value>
      <webElementGuid>82f38eae-df50-4717-9df9-6dabaf0685a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-101&quot;)</value>
      <webElementGuid>ccf8b024-c1cb-4c73-ab0e-8885a46c4a54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-101']</value>
      <webElementGuid>14d7cc31-f84e-47b7-a45b-ccf1c2c241ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/div/div/div/div/div/div/div/form/div[3]/div/div/div/input</value>
      <webElementGuid>d2d649ac-9c4c-4bcb-8ca8-18d945b17e10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>5b003c4d-98e5-4916-b252-0c9f65cfca3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-101' and @type = 'text' and @placeholder = concat(&quot;e.g @let&quot; , &quot;'&quot; , &quot;s.moot&quot;)]</value>
      <webElementGuid>24f12aa2-d368-4b55-a68a-308de730eb11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
