<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Login_v-overlay__scrim</name>
   <tag></tag>
   <elementGuidId>40293ec5-c209-42fe-b758-0d3260d2c58a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.v-overlay__scrim</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ed66b8d8-e926-4dba-af19-24fae9b8ca97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-overlay__scrim</value>
      <webElementGuid>64ef7e51-c716-4104-80c0-b116674132d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@id=&quot;app&quot;]/div[@class=&quot;v-overlay v-overlay--active theme--dark&quot;]/div[@class=&quot;v-overlay__scrim&quot;]</value>
      <webElementGuid>d286f717-7878-4522-8fdb-476481d95c44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div</value>
      <webElementGuid>0f37c714-1b47-4280-b974-9494444bc25f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div</value>
      <webElementGuid>6d342f2a-432c-4c69-86a7-bbbdebc765d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
