<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Login_v-overlay__scrim</name>
   <tag></tag>
   <elementGuidId>55ea1be3-8c7c-4246-8ec0-e5e2be23da95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.v-overlay__scrim</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>099b6e08-9b6f-402c-b3b5-4c880deb1a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-overlay__scrim</value>
      <webElementGuid>ea0a5f83-a3b3-490b-a295-bb0220f5202d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-overlay v-overlay--active theme--dark&quot;]/div[@class=&quot;v-overlay__scrim&quot;]</value>
      <webElementGuid>f3dd0c60-384e-43ca-bb2a-8ecf9f76eee3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div</value>
      <webElementGuid>283adc64-f304-46a9-9952-c4981ef13880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div</value>
      <webElementGuid>1955aade-3da5-40da-8961-14030e82bd6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
