<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_concat(Let, , s Make a thread)_v-icon not_c89c63</name>
   <tag></tag>
   <elementGuidId>95b925a5-cc7b-4dcb-90e0-4d023498bb41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/button/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mx-auto.v-btn.v-btn--block.v-btn--text.theme--light.v-size--default > span.v-btn__content > i.v-icon.notranslate.mdi.mdi-plus.theme--light</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>faf576e6-8583-4eb1-ada8-6ee80d6096d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cf16405b-3abd-4793-bfea-86fad6388263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-icon notranslate mdi mdi-plus theme--light</value>
      <webElementGuid>57a74419-506b-4460-9203-94e9c2c9cc16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[@class=&quot;container&quot;]/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/div[1]/div[@class=&quot;mx-auto mr-8 ml-8 mt-6 pa-0 rounded-lg v-card v-sheet theme--light elevation-5&quot;]/button[@class=&quot;mx-auto v-btn v-btn--block v-btn--text theme--light v-size--default&quot;]/span[@class=&quot;v-btn__content&quot;]/i[@class=&quot;v-icon notranslate mdi mdi-plus theme--light&quot;]</value>
      <webElementGuid>f806add4-77be-40a4-8b04-cabbffe005d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/button/span/i</value>
      <webElementGuid>e0ef208d-0d83-45d5-8dbb-cbec9920a5da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button/span/i</value>
      <webElementGuid>2c7ab584-c827-4d47-b026-2a1d5567f3a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
