<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_oi</name>
   <tag></tag>
   <elementGuidId>6177a87d-1754-4fb5-95f3-65539d2e8afd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.text-h4.text-bold.font-weight-medium.black--text.no-uppercase.v-btn.v-btn--plain.v-btn--router.v-btn--text.theme--light.v-size--default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>32817281-def7-4222-bd3d-11025a5e8894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/user/threads/t-vWmsRlf</value>
      <webElementGuid>2b2f1d9e-9084-44a8-a539-3f8bff52ae09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-h4 text-bold font-weight-medium black--text no-uppercase v-btn v-btn--plain v-btn--router v-btn--text theme--light v-size--default</value>
      <webElementGuid>f6521086-7dcf-4d19-a9e7-3614475e35f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        oi
      </value>
      <webElementGuid>e27fb6b6-9055-474f-a0db-3f0df72fd8c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[@class=&quot;container&quot;]/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/div[2]/div[@class=&quot;mx-auto mr-8 ml-8 mt-6 pa-4 rounded-lg v-card v-sheet theme--light elevation-5&quot;]/a[@class=&quot;text-h4 text-bold font-weight-medium black--text no-uppercase v-btn v-btn--plain v-btn--router v-btn--text theme--light v-size--default&quot;]</value>
      <webElementGuid>2cb9425c-d217-4c06-817b-55ce0f9e3527</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/a</value>
      <webElementGuid>f4dbc963-0a64-4567-b80e-e6617c288cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Let', &quot;'&quot;, 's Make a thread')])[1]/following::a[1]</value>
      <webElementGuid>9a633cdb-3d8c-40ce-a567-a17e8fc52092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Thread'])[1]/following::a[1]</value>
      <webElementGuid>24b4f2a0-59a8-4e6b-8a93-b294a476a843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='yonda'])[2]/preceding::a[1]</value>
      <webElementGuid>039d3b3c-1c6d-4d81-b7dd-8caf5249bf97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/user/threads/t-vWmsRlf')]</value>
      <webElementGuid>b1a3cd0a-1561-4366-956f-a3b2eab88a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/a</value>
      <webElementGuid>41d43540-a7e9-4703-a6b7-a8816f7c8cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/user/threads/t-vWmsRlf' and (text() = '
        oi
      ' or . = '
        oi
      ')]</value>
      <webElementGuid>901cd21b-e800-4b5c-85a4-46f1c8497613</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
