<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Create Thread</name>
   <tag></tag>
   <elementGuidId>95268c7e-4ce3-4b51-8e24-886427e6936b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/nav/div[2]/button[2]/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2acd64c6-62cc-461d-954c-f9ab36356969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-4</value>
      <webElementGuid>2ad067e6-01d0-43a1-89a1-ef509c874941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Thread</value>
      <webElementGuid>fe42d549-45c2-4728-97a8-8fc9fc860af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/nav[@class=&quot;mx-5 v-navigation-drawer v-navigation-drawer--clipped v-navigation-drawer--fixed v-navigation-drawer--is-mouseover v-navigation-drawer--open theme--light&quot;]/div[@class=&quot;v-navigation-drawer__content&quot;]/button[@class=&quot;justify-start rounded-lg no-uppercase btn-hover v-btn v-btn--has-bg theme--light elevation-0 v-size--default&quot;]/span[@class=&quot;v-btn__content&quot;]/span[@class=&quot;ml-4&quot;]</value>
      <webElementGuid>113717e2-5df8-488d-af46-b03205527a6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/nav/div[2]/button[2]/span/span</value>
      <webElementGuid>b125d3b2-fc32-45b7-9288-c9b6891aa8d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ranking'])[1]/following::span[2]</value>
      <webElementGuid>6ec3b2f7-31a9-4273-942e-dc837c692447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Culture'])[1]/following::span[4]</value>
      <webElementGuid>be6c39bd-c505-43d3-b3ab-9cfae5a5bd30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='THIS IS YOUR THREAD PAGE !!!'])[1]/preceding::span[3]</value>
      <webElementGuid>0c72606e-6225-4bdb-a100-c63c6dd3f8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create Thread']/parent::*</value>
      <webElementGuid>12358ed0-5b82-4cbb-bb21-7ac978c5bd7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span/span</value>
      <webElementGuid>3a0410f2-5b39-49c4-b5eb-5b12fc7ebdfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Create Thread' or . = 'Create Thread')]</value>
      <webElementGuid>df79b8b7-162e-4ded-b0d8-7325c8e6df2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
